////
Source: https://github.com/ethereum/yellowpaper
        https://ethereum.github.io/yellowpaper/paper.pdf
License: CC BY-SA 4.0
Added By: @fjrojasgarcia
////

[yellowpaper-guide]
= The "Yellow Paper" comprehension guide

The challenge of this simplification work is to eliminate as far as possible the barriers that hinder the understanding of the Ethereum Yellow Paper, eliminating its aridity and facilitating its understanding.

== Title, Version and Author

Title: *Ethereum: A secure decentralised generalised transaction ledger*

Version: *BYZANTIUM Version fadb37b - 2018-03-20*

Author: *Dr. Gavin Wood - Founder of Ethereum & Parity - gavin@parity.io*

== Ethereum's formal specification

This document gathers mathematically based techniques whose purpose are to help with the implementation of the Ethereum protocol.


They describe the Ethereum protocol, analyze its behavior, and aid in its design by verifying key properties of interest through rigorous and effective reasoning tools.


These specifications are formal in the sense that they have a syntax and their semantics fall within one domain.a

== Abstract explained

TODO

== Introduction

TODO

== The Blockchain Paradigm

TODO

== Conventions

TODO

== Blocks, State and Transactions

TODO

== Gas and Payment

TODO

== Transaction Execution

TODO

== Contract Creation

TODO

== Execution Model

TODO

== Blocktree to Blockchain

TODO

== Block Finalisation

TODO

== Implementing Contracts

TODO

== Future Directions

TODO

== Conclusion

TODO

== Availability

TODO

== Appendix B. Recursive Length Prefix

TODO

== Appendix D. Modified Merkle Patricia Tree

TODO

== Appendix E. Precompiled Contracts

TODO

== Appendix F. Signing Transactions

TODO

== Appendix G. Fee Schedule

TODO

== Appendix H. Virtual Machine Specification

TODO

== Appendix J. Ethash

TODO

== Appendix K. Anomalies on the Main Network

TODO

== Appendix L. List of mathematical symbols

TODO
